<?php //útf8 
//$object_to_edit = $this->getObjectToEdit();
?>
<div class="form_container form_mascota_usuario_listado">
	<form class="standart wider login" name="form1" method="post" action="<?php print $this->getUrl(Frontend_Mascota_Helper::getUrlAgregar()); ?>">
		<?php /** / ?>
		<div class="textbox">
			<div class="holding <?php //share_row half_size ?>provincia">
				<div class="input_autocomplete">
					<!-- <input type="text" autocomplete="off" title="provincia" name="provincia" id="provincia" value="">
					<div class="dropdown_button"></div>-->
					<?
						$selector_provincia = $this->appendBlock('<selector_provincia id_pais="'.$id_pais.'" parent_loader="pais" />');
						
						$id_provincia = 0;
						if($provincia){
							foreach($selector_provincia->listEntityes() as $entity){
								if($entity->getNombre()==$provincia){
									$id_provincia = $id_entity = $entity->getId();
									$selector_provincia->setSelectedValue($id_entity);
									break;
								}
							}
						}
						
						 c($selector_provincia)
							//->setSelectedValue($x->getIdpais())
							//->void($selector_pais->setSelectedValue($id_pais_argentina))
							//->void(($entityes = $selector_pais->listEntityes()) && isset($entityes[0]) && $entityes[0]->getId() && $selector_pais->setSelectedValue($entityes[0]->getId()))
//                            ->setSelectMessage('Cualquiera')
//                            ->setSelectedValue($x->getIdAgencia())
							->void($selector_provincia
								->getSelectControl()
									//->setName('provincia')
									->setId('provincia')
									->setTitle('provincia')
//									->setData('data-campo', '<b>pais</b>')
//									->setData('data-mensaje', 'Seleccione %field')
//									->setData('data-validator', '{empty:false}')
//									->setMultiple('multiple')
//									->setStyle('min-width:200px')
							)
							->toHtml()
						;
					?>
				</div>
				<!--<span class="holder">Provincia</span>-->
				<span class="help">Filtrar por nombre o descripción</span>
			</div>
		</div>
		<?php /**/ ?>
		<ul class="listado_mascotas">
			<?php while($this->moveNext()): ?> 
			<?php $class = $this->getCurrentRelativeIndex()%2?'pair':'even'; ?>
			<li class="mascota_item mascota_item_<?php print $class; ?>"><?php print $this->entityToHtml(); ?></li>
			<?php endwhile; ?>
			
			<?php if($this->getCantidadPaginas()>1):?>
			<?php $pagination_info = $this->getPaginationInfo($this->getPagina(), $this->getCantidadPaginas(), 4, 2); ?>
			<ul class="paginas">
				<!--<li class="titPaginador">P&aacute;ginas: </li>-->
				<?php if($this->getPagina()): ?> 
				<li><a href="<?php print $this->getUrlPagina(); ?>">Anterior</a></li>
				<?php else: ?> 
				<li><em>Anterior</em></li> 
				<?php endif;?> 
				<?php foreach($pagination_info as $pi): ?> 
					<?php if(!in_array($pi->getPagina(), array('',null),true)): ?> 
					<li><a href="<?php print $this->getUrlPagina($pi->getPagina()); ?>"><?php print $pagina.$pi->getLabel(); ?></a></li>
					<?php else: ?> 
					<li><em><?php print $pi->getLabel(); ?></em></li>
					<?php endif; ?> 
				<?php endforeach; ?> 
				<?php if($this->getPagina()!=($this->getCantidadPaginas()-1)): ?> 
				<li><a href="<?php print $this->getUrlPagina($this->getPagina()+1); ?>"><em>Siguiente</em></a></li>
				<?php endif; ?> 
			</ul>
			<?php endif;?> 
		</ul>
		
		
		
		<div class="form_row actions_row single_action">
			<button class="submit button" type="submit">Nueva Mascota</button>
			<ul>
				<li><a href="">Algún link</a></li>
			</ul>
			<!--
			<ul>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlServiceConditions()); ?>">Condiciones de Servicio</a></li>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlPrivacyPolicy()); ?>">Políticas de Privacidad</a></li>
			</ul>
			<ul>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlLogin()); ?>">¿Ya tienes cuenta?</a></li>
			</ul>
			-->
		</div>
	</form>
</div>      
<script type="text/javascript">
<!--
	jQuery('.link_view_mascota')
		.fancybox({
			'width': 460,
			'height':490,
	        'autoDimensions':true,
	        'transitionIn':'none',
			'transitionOut':'none',
			'type':'iframe'
		})
	;
-->
</script>