<?php //es útf8
$adopcion_conciliacions = $this->getAdopcionConciliacions();

?>

<?php if(!isset($adopcion_conciliacions)||!$adopcion_conciliacions->count()): ?> 
<h3>No has seleccionado posibles adopcion_ofertas como coincidencias</h3>
<?php return; endif; ?> 
<ul class="listado_entidad listado_mascotas listado_mascotas_adopcion_conciliacions_seleccionados listado_mascotas_adopcion_conciliacions_seleccionados_adopcion_oferta">
	<?php foreach($adopcion_conciliacions as $idx=>$adopcion_conciliacion): $class = $idx%2?'pair':'even'; ?> 
	<li class="listado_entidad_item mascota_item listado_entidad_item_<?php print $class; ?>">
		<?php
		$adopcion_oferta = $adopcion_conciliacion->getAdopcionOferta();
		echo $this->getChild('adopcion_oferta_view')
			->setAdopcionOferta($adopcion_oferta)
			->setAdopcionConciliacion($adopcion_conciliacion)
			->toHtml()
		;
		?> 
	</li>
	<?php endforeach; ?> 
</ul>
<script type="text/javascript">
<!--
	jQuery('.link_view_mascota')
		.fancybox({
			'width': 460,
			'height':490,
	        'autoDimensions':true,
	        'transitionIn':'none',
			'transitionOut':'none',
			'type':'iframe'
		})
	;
-->
</script>