<?php
$mascota = $this->getMascota();
?>
<div class="reencuentro_confirmaciones_pendientes">
	<form class="standart wider busqueda" name="form1" method="post">
		<input type="hidden" name="dummy" value="continuar" />
		<div>
			<h2>Datos de Mascota <a href="<?php print $this->getUrl($mascota->getUrlPerdidaEditar(0, 1)); ?>">Modificar</a></h2>
			<?php print $this->getChildHtml('view_datos_mascota'); ?>
		</div>
		<div>
			<h2>Posibles coincidencias que has seleccionado<a href="#no_implementado_<?php print $this->getUrl($mascota->getUrlPerdidaEditar(1, 3)); ?>">Modificar</a></h2>
			<?php print $this->getChildHtml('reencuentros_seleccionados'); ?>
		</div>
		<div>
			<h2>Coincidencias reportadas por usuario</h2>
			<?php print $this->getChildHtml('reencuentros_reportados'); ?>
		</div>
		<div class="form_row actions_row single_action">
			<!--
			<button class="submit button" type="submit">Publicar Anuncio</button>
			-->
			<ul>
				<li><a href="#">algun link</a></li>
			</ul>
		</div>
	</form>
</div>