<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="tipo_aspecto[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo TipoAspecto');
	else:
		echo $this->__t('Editar TipoAspecto');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de TipoAspecto</h3>
		<div>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('tipo_aspecto[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){
	
});

function validar_agregar_tipo_aspecto_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>