<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$arr_ponderaciones = array(
	'importancia_economica'=>Inta_Model_Config::findConfigValue('ponderacion_importancia_economica', '20'),
	'impacto_ambiental'=>Inta_Model_Config::findConfigValue('impacto_ambiental', '15'),
	'importancia_social'=>Inta_Model_Config::findConfigValue('importancia_social', '20'),
	'familias_implicadas'=>Inta_Model_Config::findConfigValue('familias_implicadas', '10'),
	'valor_agregado_potencial'=>Inta_Model_Config::findConfigValue('valor_agregado_potencial', '10'),
	'impacto_desarrollo'=>Inta_Model_Config::findConfigValue('impacto_desarrollo', '25'),
);
?><?if($this->getIdToEdit()):?>
<input type="hidden" name="problema[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); $this->setFieldsetId($id_fielset); ?>">
	<?php if(!$this->getAudienciaImplicita()): ?>
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Problema');
	else:
		echo $this->__t('Editar Problema');
	endif;?></legend>
	<fieldset>
	<?php endif; ?>
		<h3>Informacion de Problema</h3>
		<div>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setSize(56)
					->setName('problema[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre de Problema</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<?php if(!$this->getAudienciaImplicita()): ?>
			<label>Audiencia: </label>
			<span><?
				/** /
				echo c($selector_audiencia = $this->appendBlock('<selector_audiencia />'))
					->setSelectedValue($x->getIdAudiencia())
					->void($selector_audiencia
						->getSelectControl()
							->setName('problema[id_audiencia]')
							->setId('id_audiencia')
							->setData('data-campo', '<b>Audiencia</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
				/**/
				echo c($selector_audiencia = $this->appendBlock('<selector_audiencia_abm />'))
					->setSelectedValue($x->getIdAudiencia())
					->void($selector_audiencia
						->getSelectControl()
							->setName('problema[id_audiencia]')
							->setId('id_audiencia')
							->setData('data-campo', '<b>Audiencia</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
				//
			?> 
			</span>
			<?php endif; ?>
			<label>Importancia Econ&oacute;mica: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('importancia_economica')
					->setData('data-ponderacion', $arr_ponderaciones[$input->getId()])
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[importancia_economica]')
					->setValue($x->getImportanciaEconomica()+0)
					->setData('data-campo', '<b>Importancia Econ&oacute;mica:</b>')
					->setData('data-validator', '{empty:false,decimal:2}')
				;
				echo $input->getHtml();
			?></label>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#importancia_economica', 'min'=>0,'max'=>5, 'step'=>1, 'fixed'=>0))); ?>"></div>
			<label>Impacto Ambiental: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('impacto_ambiental')
					->setData('data-ponderacion', $arr_ponderaciones[$input->getId()])
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[impacto_ambiental]')
					->setValue($x->getImpactoAmbiental()+0)
					->setData('data-campo', '<b>Impacto Ambiental:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?></label>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#impacto_ambiental', 'min'=>0,'max'=>5, 'step'=>1, 'fixed'=>0))); ?>"></div>
			<label>Importancia Social: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('importancia_social')
					->setData('data-ponderacion', $arr_ponderaciones[$input->getId()])
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[importancia_social]')
					->setValue($x->getImportanciaSocial()+0)
					->setData('data-campo', '<b>Importancia Social:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?></label>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#importancia_social', 'min'=>0,'max'=>5, 'step'=>1, 'fixed'=>0))); ?>"></div>
			<label>Familias Implicadas: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('familias_implicadas')
					->setData('data-ponderacion', $arr_ponderaciones[$input->getId()])
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[familias_implicadas]')
					->setValue($x->getFamiliasImplicadas()+0)
					->setData('data-campo', '<b>Familias Implicadas:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?></label>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#familias_implicadas', 'min'=>0,'max'=>5, 'step'=>1, 'fixed'=>0))); ?>"></div>
			<label>Valor Agregado Potencial: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('valor_agregado_potencial')
					->setData('data-ponderacion', $arr_ponderaciones[$input->getId()])
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[valor_agregado_potencial]')
					->setValue($x->getValorAgregadoPotencial()+0)
					->setData('data-campo', '<b>Valor Agregado Potencial:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?></label>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#valor_agregado_potencial', 'min'=>0,'max'=>5, 'step'=>1, 'fixed'=>0))); ?>"></div>
			<label>Impacto de Desarrollo del Territorio: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('impacto_desarrollo')
					->setData('data-ponderacion', $arr_ponderaciones[$input->getId()])
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[impacto_desarrollo]')
					->setValue($x->getImpactoDesarrollo()+0)
					->setData('data-campo', '<b>Impacto de Desarrollo del Territorio:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?></label>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#impacto_desarrollo', 'min'=>0,'max'=>5, 'step'=>1, 'fixed'=>0))); ?>"></div>
			<label>Prioridad: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setId('prioridad')
					->setType('text')
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setName('problema[prioridad]')
					->setValue($x->getPrioridad()+0)
					//->setValue($x->getImpactoDesarrollo()+0)
					//->setData('data-campo', '<b>Impacto de Desarrollo del Territorio:</b>')
					//->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?></label>
			<input type="button" class="actualizar" value="Actualizar Prioridad" style="display:none;" />
		</div>
	<?php if(!$this->getAudienciaImplicita()): ?>
	</fieldset>
	
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
	<?php endif; ?>
</fieldset>
<script>
function calcular_prioridad(){
	var total = 0;
	jQuery('[data-ponderacion]').each(function(){
		var ponderacion = jQuery(this).attr('data-ponderacion');
		total += parseFloat(this.value) * parseFloat(ponderacion) / 100;
	});
	return total.toFixed(2);
}
jQuery(document).ready(function(){
	var prioridad_nueva = calcular_prioridad();
	var prioridad_vieja = parseFloat(jQuery('#prioridad').val());
	if(prioridad_nueva!=prioridad_vieja){
		jQuery('.actualizar').click(function(){
			jQuery('#prioridad').val(calcular_prioridad());
		}).show();
	}
	jQuery('[data-ponderacion]').change(function(){
		jQuery('#prioridad').val(calcular_prioridad());
	});
    jQuery('.slider').each(function(){
    	jQuery(this).css('margin-top', '9px');
		var data = jQuery(this).attr('data-info');
		var options = null;
		try{
			eval('options='+data);
		}
		catch(e){
			alert("kradkk");
			return;
		}
		options.value = jQuery(options.target).val();
		options.slide = function(event, ui){
			var val = ui.value;
			if(options.fixed){
				val = (new Number(parseFloat(val))).toFixed(options.fixed);
			}
			jQuery(options.target).val(val);
		}
		options.change = function(){jQuery(options.target).change()}
		jQuery(this).slider(options);
		//jQuery(options.target).val(ui.value);
	})
	//$("#amount").val('$' + $("#slider").slider("value"));
});

function validar_agregar_problema_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>