<div class="<?php print $id = $this->generateRandomId(); ?>">
	<table border="1" cellpadding="0" cellspacing="0" style="width:100%;">
		<thead>
			<tr>
				<td>Descripcion</td>
				<td>Ejecutar</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php print htmlentities('Regenerar Cache de búsqueda'); ?></td>
				<td>
					<a href="#" class="iniciar_regenerar_cache_busqueda">Iniciar</a>
				</td>
			</tr>
                        <tr>
				<td><?php print htmlentities('Generar Sitemap'); ?></td>
				<td>
					<a href="#" class="generar_sitemap">Iniciar</a>
				</td>
			</tr>
		</tbody>
	</table>
	<div style="display:none;">
		<div class="wait_window">
			<div class="message"></div>
			<img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" />
		</div>
	</div>
</div>



<script>
jQuery(document).ready(function(){
	var jqcontrol = jQuery('.<?php print $id; ?>')
	jqcontrol.find('.iniciar_regenerar_cache_busqueda').click(function(){
		try{
			var jqwindow = jqcontrol.find('.wait_window');
			jqwindow.find('.message').text('<?php print utf8_encode('Regenerando caché de búsqueda'); ?>');
			jQuery.blockUI({
				message: jqwindow
			});
			jQuery.get(
				'<?php print $this->getUrl('administrator/config/regenerar_cache_busqueda'); ?>',
				function(data){
					jQuery.unblockUI();
					if(data){
						var jqmessage = jQuery('<div></div>').html(data);
						jQuery('<br/>').appendTo(jqmessage);
						var jqclose_button = jQuery('<input type="button" />').val('cerrar').click(function(){jQuery.unblockUI();}).appendTo(jqmessage);
						jQuery.blockUI({
							message: jqmessage
						});
					}
				}
			)
		}catch(e){alert(e);}
		return false;
	});
        jqcontrol.find('.generar_sitemap').click(function(){
		try{
			var jqwindow = jqcontrol.find('.wait_window');
			jqwindow.find('.message').text('<?php print utf8_encode('Generando Sitemap'); ?>');
			jQuery.blockUI({
				message: jqwindow
			});
			jQuery.get(
				'<?php print $this->getUrl('administrator/sitemap/generar'); ?>',
				function(data){
					jQuery.unblockUI();
					if(data){
						var jqmessage = jQuery('<div></div>').html(data);
						jQuery('<br/>').appendTo(jqmessage);
						var jqclose_button = jQuery('<input type="button" />').val('cerrar').click(function(){jQuery.unblockUI();}).appendTo(jqmessage);
						jQuery.blockUI({
							message: jqmessage
						});
					}
				}
			)
		}catch(e){alert(e);}
		return false;
	});
});
</script>