<?php 
if(!$this->hasEntityToList()||!$this->getEntityToList()){?> 
	error, no hay entidad para el control <?php print get_class($this); ?><?
	return;
}

	$html_select = '';
	if($options = $this->createOptions())
		foreach($options as $option)
			$html_select .= $option->getHtml();
	
	$c = $this->getSelectControl();

?>
<div class="<?php print $id = uniqid(); ?>">
<?php 	echo $c
		->setInnerHtml($html_select)
		->getHtml()
	;?>
</div>
<script type="text/javascript">
jQuery(function(){
//	try{
//		jQuery('.<?php print $id; ?> select').selectmenu();
//	}
//	catch(e){
//		alert(jQuery('.<?php print $id; ?> select').selectmenu.toString());
//	}
})
</script>