<script type="text/javascript">
//jQuery.localise('ui-multiselect', {timeout:5000, language: 'es', path: '<?php print dirname($this->getSkinUrl('jquery-ui-1.8.1.custom/locale/ui-multiselect-es.js')); ?>/'});
if(window.isArray == null){
	window.isArray = function(obj) {
		if((typeof obj) != 'object')
			return false;
		if (obj.constructor.toString().indexOf("Array") == -1)
			return false;
		return true;
	}
}
(function (c, d, e, f, g) {
	try{
	    if (typeof d != "object" && typeof d != "string") {
	        g = f;
	        f = e;
	        e = d;
	        d = "";
	    }
	    if (typeof e != "boolean") {
	        g = f;
	        f = e;
	        e = false;
	    }
		if(f==null){
	        g = f;
	        f = ["", ""];
		}
	    else if(typeof f != "string" && !isArray(f)) {
	        g = f;
	        f = ["", ""];
	    }
	    d = typeof d != "string" ? d || {} : {language: d, loadBase: e, path: f, timeout: g};
	    var j = !d.path ? ["", ""] : isArray(d.path) ? d.path : [d.path, d.path];
	    var k = function (a, b) {if (d.loadBase) {$.getScript(j[0] + a + (".js"));}if (b.length >= 2) {$.getScript(j[1] + a + ("-" + b.substring(0, 2) + ".js"));}if (b.length >= 5) {$.getScript(j[1] + a + ("-" + b.substring(0, 5) + ".js"));}};
	    var l = /*normaliseLang*/(d.language || $.localise.defaultLanguage);
	    c = isArray(c) ? c : [c];
	    for (i = 0; i < c.length; i++) {
	        k(c[i], l);
	    }
	}
	catch(e){
		alert("no se pudo inicializar page/multiselect-init.phtml");
	}

})('ui-multiselect', {language: 'es', path: '<?php print dirname($this->getSkinUrl('jquery-ui-1.8.1.custom/locale/ui-multiselect-es.js')); ?>/'});
</script>