<?php //es útf8

$mascota = $this->getMascota();

//var_dump(get_class($mascota),$mascota->getData());
//die(__FILE__.__LINE__);
?> 
	<div class="image">
		<img src="<?php print $mascota->getUrlImage(70, 78); ?>" />
	</div>
	<ul class="column1">
		<li>
			<b>Nombre:</b>
			<em><?php print $mascota->getNombre(); ?></em>
		</li>
		<li>
			<b>Sexo:</b>
			<em><?php print $mascota->getSexo(); ?></em>
		</li>
		<li>
			<b>Edad:</b>
			<em><?php print $mascota->calcularEdad(); ?></em>
		</li>
		<li>
			<b>Raza:</b>
			<em><?php print $mascota->getRaza()->getNombre(); ?></em>
		</li>
	</ul>
	<ul class="column2">
		<li>
			<b>Estado:</b>
			<em><?php print $mascota->getEstadoFull(); ?></em>
		</li>
		<li>
			<a class="link_view_mascota" href="<?php print $this->getUrl($mascota->getUrlSimpleView()); ?>">Ver todos los datos</a>
		</li>
	</ul>
	<div style="clear:both;float:none;"></div>