<?php //útf8
$object_to_edit = $this->getObjectToEdit();
$domicilio_usuario = $this->getDomicilioUsuario();
$midomicilio = $object_to_edit->getMidomicilio();
$midomicilio = $midomicilio==''?'no':$midomicilio;
$midomicilio = $midomicilio=='si'&&!$domicilio_usuario?'no':$midomicilio;

?>

		<?php if($domicilio_usuario): ?>
		<div class="selector_midomicilio">
			<?php
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					//->setMaxlength(20)
					->setType('radio')
					//->setAutocomplete('off')
					->setTitle('Mi domicilio')
					//->setClass('datepicker')
					->setName('midomicilio')
					->setId('midomicilio_si')
					->setValue('si')
				;
				if($midomicilio=='si')
					$input->setChecked('checked');
				echo $input->getHtml();
			?> 
			<label for="midomicilio_si">Mi domicilio</label>
			<?php
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					//->setMaxlength(20)
					->setType('radio')
					//->setAutocomplete('off')
					->setTitle('Otro domicilio')
					//->setClass('datepicker')
					->setName('midomicilio')
					->setId('midomicilio_no')
					->setValue('no')
				;
				if($midomicilio=='no')
					$input->setChecked('checked');
				echo $input->getHtml();
			?> 
			<label for="midomicilio_no">Otro domicilio</label>
		</div>
		<div class="midomicilio_si_contenido midomicilio_contenido"<?php if($midomicilio=='no'): ?> style="display:none;"<?php endif; ?>>
			<ul>
				<li>
					<strong>País</strong>: <em><?php print htmlentities(utf8_decode($domicilio_usuario->getPais()))?></em>
					<strong>Provincia</strong>: <em><?php print htmlentities(utf8_decode($domicilio_usuario->getProvincia()))?></em>
					<strong>Localidad</strong>: <em><?php print htmlentities(utf8_decode($domicilio_usuario->getLocalidad()))?></em>
					<strong>Barrio</strong>: <em><?php print htmlentities(utf8_decode($domicilio_usuario->getBarrio()->getNombre()))?></em>
					<strong>Domicilio</strong>: <em><?php print htmlentities(utf8_decode($domicilio_usuario->getCalleNumero()))?></em>
				</li>
			</ul>
		</div>
		<?php else: ?>
		<input type="hidden" name="midomicilio" value="no" />
		<?php endif; ?> 
		<div class="midomicilio_no_contenido midomicilio_contenido"<?php if($midomicilio=='si'): ?> style="display:none;"<?php endif; ?>>
		<?php print $this->getChildHtml(); ?> 
		</div>