<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


?><?if($this->getIdToEdit()):?>
<input type="hidden" name="aspecto_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="aspecto_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo AspectoActividad');
	else:
		echo $this->__t('Editar AspectoActividad');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de AspectoActividad</h3>
		<div>
			<label>Aspecto: </label>
			<span><?
				echo c($selector_tipo_aspecto = $this->appendBlock('<selector_aspecto />'))
					->setSelectedValue($x->getIdAspecto())
					->void($selector_tipo_aspecto
						->getSelectControl()
							->setName('aspecto_actividad[id_aspecto]')
							->setId('id_aspecto')
							->setData('data-campo', '<b>Aspecto</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
			?> 
			</span>
			<label>Detalle: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('aspecto_actividad[nombre_extendido]')
					->setValue($x->getNombreExtendido())
//					->setData('data-campo', '<b>Detalle</b>')
//					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

function aspecto_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_aspecto_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>