<div class="listado_aspecto_actividads" id="<?php print $id_control_big = $this->generateRandomId(); ?>"><?
$aspecto_actividads = $this->getAspectoActividads();
if($aspecto_actividads){
	echo '<ul class="box_listado_aspecto_actividads" id="'.($id_control = $this->generateRandomId()).'">';
	foreach($aspecto_actividads as $aspecto_actividad){
		echo
			'<li data-id="'.$aspecto_actividad->getId().'">'. 
			'<span>'.$aspecto_actividad->getNombreCompuesto().'</span>';
		?>
		<div class="listado_toolbox listado_toolbox_aspecto_actividads">
			<div class="btn_eliminar btn_eliminar_aspecto_actividad" title="Eliminar AspectoActividad"></div>
			<div class="btn_editar btn_editar_aspecto_actividad" title="Editar AspectoActividad"></div>
		</div><?php
		echo '</li>';
	}
	echo '</ul>';?> 
<script>
jQuery(document).ready(function(){
	var jqicon = jQuery('#<?php print $id_control?> .show_icon');
	jQuery('#<?php print $id_control?>>li')
		.timemouse({
			mouseover: function(){
				jQuery(this).addClass('thover')
			},
			mouseout: function(){
				jQuery(this).removeClass('thover')
			}, 
			time: 0
		})
	;

	jQuery('#<?php print $id_control?> .btn_eliminar_aspecto_actividad')
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFDDDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var jqwin = jQuery('<div></div>');
			jqwin.html('&iquest;Desea continuar eliminando el aspecto_actividad?<br />');
			var jqaceptar = jQuery('<input type="button" value="Continuar" />')
				.click(function(){
					var id_aspecto_actividad = jqthat.parents('li:first').attr('data-id');
					var jqwait = jQuery('<div></div>');
					jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
					jqwait.ScreenBlock();
					jQuery.get(
						'administrator/ajax/aspecto_actividad/delete/'+id_aspecto_actividad+'/',
						function (data){
							jQuery.ScreenBlock(false);
							jQuery('#<?php print $id_control; ?>')
								.parents('.listado_aspecto_actividads:first')
								.html(data)
							;
						}
					)
				})
				.appendTo(jqwin)
			;
			var jqcancelar = jQuery('<input type="button" value="Cancelar" />')
				.click(function(){
					jQuery.ScreenBlock(false);
				})
				.appendTo(jqwin)
			;
			jqwin.ScreenBlock();
		})
	;
	jQuery('#<?php print $id_control?> .btn_editar_aspecto_actividad')
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFFFBB')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var id_aspecto_actividad = jqthat.parents('li:eq(0)').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'<?php print 'administrator/ajax/aspecto_actividad/addEdit/'.$this->getIdActividad().'/'; ?>'+id_aspecto_actividad,
				{
					target: '#'+jQuery('#<?php print $id_control; ?>').parents('.listado_aspecto_actividads:last').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			)
		})
	;

})
</script><?
	
}
else{
//echo "no hay docs";
	if($this->getShowEmptyMessage()){?> 
		<h3>No hay Aspectos cargados</h3><?
	}
}
?>
</div>