<?php //útf8 ?>
<form method="post" class="standart signup signup-btn" action="https://twitter.com/signup">
  <div class="holding name">
    <input type="text" maxlength="20" name="user[name]" value="" autocomplete="off">
    <span class="holder">Nombre completo</span>
  </div>
  <div class="holding email">
    <input type="text" name="user[email]" value="" autocomplete="off">
    <span class="holder">Correo electrónico</span>
  </div>
  <div class="holding password">
    <input type="password" name="user[user_password]" value="">
    <span class="holder">Contraseña</span>
  </div>
  
  <input type="hidden" name="context" value="front">
  <input type="submit" value="Regístrate" class="promotional submit button">
</form>