<?php //útf8 ?>
<div class="form_container form_login">
	<form class="standart login" name="form1" method="post">
		<div class="textbox">
			<div class="holding password">
				<input type="password" autocomplete="on" title="password" name="current_password" value="">
				<span class="holder">Contrase&ntilde;a Actual</span>
				<span class="help">Ingresa tu contraseña actual</span>
			</div>
		</div>
		<div class="textbox">
			<div class="holding new_password">
				<input type="password" autocomplete="on" title="new_password" name="new_password" value="">
				<span class="holder">Nueva Contrase&ntilde;a</span>
				<span class="help">Ingresa la nueva contraseña</span>
			</div>
		</div>
		<div class="textbox">
			<div class="holding new_password2">
				<input type="password" autocomplete="on" title="new_password2" name="new_password2" value="">
				<span class="holder">Nueva Contrase&ntilde;a</span>
				<span class="help">Repite la nueva contraseña</span>
			</div>
		</div>
		<div class="form_row actions_row single_action">
			<button class="submit button" type="submit">Actualizar Contraseña</button>
			<ul>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlUpdate()); ?>">Modificar Datos</a></li>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlUpdateAddress()); ?>">Modificar domicilio</a></li>
			</ul>
			<ul>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlServiceConditions()); ?>">Condiciones de Servicio</a></li>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlPrivacyPolicy()); ?>">Políticas de Privacidad</a></li>
			</ul>
		</div>
	</form>
</div>      
