<?php //es útf8

$mascota = $this->getEntity();

//var_dump(get_class($mascota),$mascota->getData());
//die(__FILE__.__LINE__);
?> 
	<div class="image">
		<img src="<?php print $mascota->getUrlImage(70, 78); ?>" />
	</div>
	<ul class="column1">
		<li>
			<b>Nombre:</b>
			<em><?php print $mascota->getNombre(); ?></em>
		</li>
		<li>
			<b>Sexo:</b>
			<em><?php print $mascota->getSexo(); ?></em>
		</li>
		<li>
			<b>Edad:</b>
			<em><?php print $mascota->calcularEdad(); ?></em>
		</li>
		<li>
			<b>Raza:</b>
			<em><?php print $mascota->getRaza()->getNombre(); ?></em>
		</li>
	</ul>
	<ul class="column2">
		<li>
			<b>Estado:</b>
			<em><?php print $mascota->getEstadoFull(); ?></em>
		</li>
		<li>
			<a class="link_view_mascota" href="<?php print $this->getUrl($mascota->getUrlSimpleView()); ?>">Ver todos los datos</a>
			<a href="<?php print $this->getUrl($mascota->getUrlEditar()); ?>">Modificar o agregar fotos</a>
			<ul class="multilink">
				<?php if($mascota->esEstadoPerdida()): ?> 
				<li><a href="#no_implementado">Ya lo encontré</a></li>
				<?php else: ?> 
					<?php if($mascota->esEstadoConDueno()): ?>
					<li><a href="<?php print $this->getUrl($mascota->getUrlPerdidaEditar()); ?>">Lo perdí</a></li> 
						<?php if(!$mascota->esParaCruza()): ?>
						<li><a href="<?php print $this->getUrl($mascota->getUrlSetParaCruza()); ?>">Quiero cruzarlo</a></li>
						<?php endif; ?>
						<?php if(!$mascota->esParaVenta()): ?>
						<li><a href="<?php print $this->getUrl($mascota->getUrlSetParaVenta()); ?>">Quiero venderlo</a></li>
						<?php endif; ?>
					<?php endif; ?> 
					<?php if(!$mascota->esParaAdoptar() && !$mascota->esEstadoVista()): ?>
					<li><a href="<?php print $this->getUrl($mascota->getUrlSetParaAdoptar()); ?>">Quiero regalar</a></li>
					<?php endif; ?>
				<?php endif; ?>
				<?php if($mascota->hasReencuentros()): ?> 
				<li><a href="<?php print $this->getUrl($mascota->getUrlConfirmacionesPendientes()); ?>">Confirmaciones Pendientes</a></li>	
				<?php endif; ?> 
			</ul>
		</li>
	</ul>
	<div style="clear:both;float:none;"></div>