<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();



?><?if($this->getIdToEdit()):?>
<input type="hidden" name="proyecto_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="proyecto_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo ProyectoActividad');
	else:
		echo $this->__t('Editar ProyectoActividad');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de ProyectoActividad</h3>
		<div>
			<label>Proyecto: </label>
			<span><?
				echo c($selector_proyecto = $this->appendBlock('<selector_proyecto />'))
					->setSelectedValue($x->getIdProyecto())
					->void($selector_proyecto
						->getSelectControl()
							->setName('proyecto_actividad[id_proyecto]')
							->setId('id_proyecto')
							->setData('data-campo', '<b>Proyecto</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
			?> 
			</span>
			<label>Monto: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(50)
					->setId('monto')
					->setName('proyecto_actividad[monto]')
					->setValue($x->getMonto())
					->setData('data-campo', '<b>Monto</b>')
					->setData('data-validator', '{empty:false,decimal:2}')
					->setData('data-mensaje', '%field debe ser numerico de 2 decimales')
				;
				echo $input->getHtml();
			?> 
			</span>
			
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

function proyecto_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_proyecto_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>