<div class="listado_proyecto_actividads" id="<?php print $id_control_big = $this->generateRandomId(); ?>"><?
$proyecto_actividads = $this->getProyectoActividads();
if($proyecto_actividads){
	$total = 0;
	echo '<ul class="box_listado_proyecto_actividads" id="'.($id_control = $this->generateRandomId()).'">';
	foreach($proyecto_actividads as $proyecto_actividad){
		echo
			'<li data-id="'.$proyecto_actividad->getId().'">'. 
			'<span>'.$proyecto_actividad->getNombre().'</span><br />'.
			'<i>Presupuesto estimado: $'.$proyecto_actividad->getMonto().'</i>';
		$total += floatval($proyecto_actividad->getMonto());
		?>
		<div class="listado_toolbox listado_toolbox_proyecto_actividads">
			<div class="btn_eliminar btn_eliminar_proyecto_actividad" title="Eliminar ProyectoActividad"></div>
			<div class="btn_editar btn_editar_proyecto_actividad" title="Editar ProyectoActividad"></div>
		</div><?php
		echo '</li>';
	}
	echo '</ul>';?> 
	<div class="total">Total <i><?php print $total; ?></i></div>
<script>
jQuery(document).ready(function(){
	var jqicon = jQuery('#<?php print $id_control?> .show_icon');
	jQuery('#<?php print $id_control?>>li')
		.timemouse({
			mouseover: function(){
				jQuery(this).addClass('thover')
			},
			mouseout: function(){
				jQuery(this).removeClass('thover')
			}, 
			time: 0
		})
	;

	jQuery('#<?php print $id_control?> .btn_eliminar_proyecto_actividad')
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFDDDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var jqwin = jQuery('<div></div>');
			jqwin.html('&iquest;Desea continuar eliminando el proyecto_actividad?<br />');
			var jqaceptar = jQuery('<input type="button" value="Continuar" />')
				.click(function(){
					var id_proyecto_actividad = jqthat.parents('li:first').attr('data-id');
					var jqwait = jQuery('<div></div>');
					jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
					jqwait.ScreenBlock();
					jQuery.get(
						'administrator/ajax/proyecto_actividad/delete/'+id_proyecto_actividad+'/',
						function (data){
							jQuery.ScreenBlock(false);
							jQuery('#<?php print $id_control; ?>')
								.parents('.listado_proyecto_actividads:first')
								.html(data)
							;
						}
					)
				})
				.appendTo(jqwin)
			;
			var jqcancelar = jQuery('<input type="button" value="Cancelar" />')
				.click(function(){
					jQuery.ScreenBlock(false);
				})
				.appendTo(jqwin)
			;
			jqwin.ScreenBlock();
		})
	;
	jQuery('#<?php print $id_control?> .btn_editar_proyecto_actividad')
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFFFBB')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var id_proyecto_actividad = jqthat.parents('li:eq(0)').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'<?php print 'administrator/ajax/proyecto_actividad/addEdit/'.$this->getIdActividad().'/'; ?>'+id_proyecto_actividad,
				{
					target: '#'+jQuery('#<?php print $id_control; ?>').parents('.listado_proyecto_actividads:last').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			)
		})
	;

})
</script><?
	
}
else{
//echo "no hay docs";
	if($this->getShowEmptyMessage()){?> 
		<h3>No hay Proyectos cargados</h3><?
	}
}
?>
</div>