<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="aspecto[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Aspecto');
	else:
		echo $this->__t('Editar Aspecto');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de Aspecto</h3>
		<div>
			<label>Tipo Aspecto: </label>
			<span><?
				echo c($selector_tipo_aspecto = $this->appendBlock('<selector_tipo_aspecto />'))
					->setSelectedValue($x->getIdTipoAspecto())
					->void($selector_tipo_aspecto
						->getSelectControl()
							->setName('aspecto[id_tipo_aspecto]')
							->setId('id_tipo_aspecto')
							->setData('data-campo', '<b>Tipo Aspecto</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
			?> 
			</span>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('aspecto[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){

});

function validar_agregar_aspecto_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>