<?php //útf8 
//$object_to_edit = $this->getObjectToEdit();
?>
<div class="div_container notificacion_usuario_listado_view">
	<div class="notificacion_usuario_listado">
		<table>
			<colgroup>
				<col width="2" />
				<col />
				<col width="1" />
			</colgroup>
			<thead>
				<tr>
					<th>
						De
					</th>
					<th>
						Asunto
					</th>
					<th>
						Fecha
					</th>
				</tr>
			</thead>
			<tbody>
				<?php while($this->moveNext()): ?> 
				<?php $class = $this->getCurrentRelativeIndex()%2?'pair':'even'; ?>
				<tr class="notificacion_item notificacion_item_<?php print $this->getCurrentEntity()->esLeida()?'leida':'no_leida'; ?> notificacion_item_<?php print $class; ?>">
					<?php print $this->entityToHtml(); ?>
				</tr>
				<?php endwhile; ?> 
			</tbody>
			<tfoot>
				<tr>
					<td colspan="3">
						<?php if($this->getCantidadPaginas()>1):?>
						<?php $pagination_info = $this->getPaginationInfo($this->getPagina(), $this->getCantidadPaginas(), 2, 3); ?>
						<ul class="paginas">
							<!--<li class="titPaginador">P&aacute;ginas: </li>-->
							<?php if($this->getPagina()): ?> 
							<li><a href="<?php print $this->getUrlPagina(); ?>">Anterior</a></li>
							<?php else: ?> 
							<li><em>Anterior</em></li> 
							<?php endif;?> 
							<?php foreach($pagination_info as $pi): ?> 
								<?php if(!in_array($pi->getPagina(), array('',null),true)): ?> 
								<li><a href="<?php print $this->getUrlPagina($pi->getPagina()); ?>"><?php print $pagina.$pi->getLabel(); ?></a></li>
								<?php else: ?> 
								<li><em><?php print $pi->getLabel(); ?></em></li>
								<?php endif; ?> 
							<?php endforeach; ?> 
							<?php if($this->getPagina()!=($this->getCantidadPaginas()-1)): ?> 
							<li><a href="<?php print $this->getUrlPagina($this->getPagina()+1); ?>"><em>Siguiente</em></a></li>
							<?php endif; ?> 
						</ul>
						<?php endif;?> 
					</td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>