<?php
if(!$this->hasIdActividad()&&!$this->hasAllowInNew()){
	echo  ("no hay actividad a editar ".__FILE__.'-'.__LINE__);
	return;
}

?>
<div class="add_edit_list add_edit_list_resultado_esperado_actividads <?php print $id_control=$this->generateRandomId(); ?>" data-json="<?php print htmlentities(json_encode(array('id_actividad'=>$this->getIdActividad(), 'target'=>'.'.$id_control.' .listado_resultado_esperado_actividads'))); ?>">
	<?php if(!$this->getViewOnly()): ?>
	<div class="add_edit_list_toolbox add_edit_list_toolbox_resultado_esperado_actividads">
		<div class="btn_agregar btn_agregar_resultado_esperado_actividad" title="Agregar ResultadoEsperadoActividad"></div>
		<div class="btn_refresh btn_refresh_resultado_esperado_actividad" title="Actualizar ResultadoEsperadoActividad"></div>
	</div>
	<?php endif; ?>
	<?php print $this->getListadoResultadoEsperadoActividadsToHtml(); ?> 
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	var jqform = jQuery('.<?php print $id_control; ?>');
	
	jQuery('.btn_refresh_resultado_esperado_actividad', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#DDFFDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var jqlistado = jqthat.parents('.add_edit_list_resultado_esperado_actividads:first');
			var data = jqlistado.data('data-jso');
			if(data==null){
				try{
					eval('data='+jqlistado.attr('data-json'));
				}catch(e){
				}
				if(data==null)
					return;
			}
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'administrator/ajax/resultado_esperado_actividad/listarResultadoEsperadoActividad/'+(data.id_actividad?data.id_actividad:'')+'/',
				function (dataret){
					jqwait.ScreenBlock(false);
					jQuery(data.target).html(dataret);
				}
			);
		})
	;
	jQuery('.btn_agregar_resultado_esperado_actividad', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#DDFFDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var jqlistado = jqthat.parents('.add_edit_list_resultado_esperado_actividads:first');
			var data = jqlistado.data('data-jso');
			if(data==null){
				try{
					eval('data='+jqlistado.attr('data-json'));
				}catch(e){
				}
				if(data==null)
					return;
			}
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'administrator/ajax/resultado_esperado_actividad/addEdit/'+(data.id_actividad?data.id_actividad:'')+'/',
				{
					target: data.target
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_container_css:{'text-align':'left'},message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			);
		})
	;
});
<?php if($this->getValidator()): ?> 
//alert("<?php print $this->getValidator(); ?>");
function <?php print $this->getValidator(); ?>(){
	ok = jQuery('.<?php print $id_control; ?> .box_listado_resultado_esperado_actividads li').length>0;
	if(ok){
		return true;
	}
	show_messages(['Seleccione al menos un resultado esperado'], true);
	tabpanelfocus(jQuery('.<?php print $id_control; ?>'));
	return false;
}
<?php endif; ?>
</script>