<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


?><?if($this->getIdToEdit()):?>
<input type="hidden" name="resultado_esperado_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="resultado_esperado_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo ResultadoEsperadoActividad');
	else:
		echo $this->__t('Editar ResultadoEsperadoActividad');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de ResultadoEsperadoActividad</h3>
		<div>
			<label>Resultado Esperado: </label>
			<span><?
				//echo c($selector_resultado_esperado = $this->appendBlock('<selector_resultado_esperado />'))
				c($selector_resultado_esperado = $this->appendBlock('<selector_resultado_esperado_objetivo_simple />'))
				
					->setSelectedValue($x->getIdResultadoEsperado())
					->void($selector_resultado_esperado
						->getSelectControl()
							->setName('resultado_esperado_actividad[id_resultado_esperado]')
							->setId('id_resultado_esperado')
							->setData('data-campo', '<b>Resultado Esperado</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
				;
				if(!$x->getIdResultadoEsperado()){
					$opt = array($x->getIdObjetivo());
					$selector_resultado_esperado->setChainOptions($opt);
				}
				echo $selector_resultado_esperado
					->toHtml()
				;
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

function resultado_esperado_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_resultado_esperado_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>