<?php
if(!$this->hasIdEntidad()||!$this->hasTipoEntidad()){
	echo  ("no hay entidad a editar ".__FILE__.'-'.__LINE__);
	return;
}
//$x = $this->getObjectToEdit();

//var_dump($this->getIdEntidad(), $this->getTipoEntidad());

//echo $this->getChildHtml('listado_documentos');

?>
<div class="add_edit_list add_edit_list_documentos <?php print $id_control=$this->generateRandomId(); ?>" data-json="<?php print htmlentities(json_encode(array('tipo_entidad'=>$this->getTipoEntidad(), 'id_entidad'=>$this->getIdEntidad(), 'target'=>'.'.$id_control.' .listado_documentos'))); ?>">
	<div class="add_edit_list_toolbox add_edit_list_documentos_toolbox">
		<div class="btn_agregar_documento btn_agregar_indicador_attach" title="Agregar Documento"></div>
		<div class="btn_refresh btn_refresh_indicador_attach" title="Actualizar Documentos"></div>
	</div>
	<?php print $this->getListadoDocumentosToHtml(); ?> 
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	var jqform = jQuery('.<?php print $id_control; ?>');
	
	jQuery('.btn_refresh_indicador_attach', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#DDFFDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var jqlistado = jqthat.parents('.add_edit_list_documentos:first');
			var data = jqlistado.data('data-jso');
			if(data==null){
				try{
					eval('data='+jqlistado.attr('data-json'));
				}catch(e){
				}
				if(data==null)
					return;
			}
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'administrator/ajax/documento/listarDocumentos/'+data.tipo_entidad+'/'+data.id_entidad+'/',
				function (dataret){
					jqwait.ScreenBlock(false);
					jQuery(data.target).html(dataret);
				}
			);
		})
	;
	jQuery('.btn_agregar_indicador_attach', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#DDFFDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var jqlistado = jqthat.parents('.add_edit_list_documentos:first');
			var data = jqlistado.data('data-jso');
			if(data==null){
				try{
					eval('data='+jqlistado.attr('data-json'));
				}catch(e){
				}
				if(data==null)
					return;
			}
			var id_medio_verificacion_indicador_resultado = jqthat.parents('li:first').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'administrator/ajax/documento/addEdit/'+data.tipo_entidad+'/'+data.id_entidad+'/',
				{
					target: data.target//'#'+jQuery('#<?php print $id_control; ?>').parents('.ui-tabs-panel:first').attr('id')+' .medios_verificacion_indicador_resultado>li[data-id='+id_medio_verificacion_indicador_resultado+'] .listado_documentos'
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			);
		})
	;
	<?php if($this->getFocusTab()): ?> 
	setTimeout(
		function(){
			tabpanelfocus(jQuery('.<?php print $id_control; ?>'));
		}
		, 500
	);
	<?php endif; ?>
});

</script>