<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();
$configcke1 = array(
	'config'=>array(
		'toolbar' => 'Basic',
		'toolbarStartupExpanded'=> false,
		'width'=>'663px',
		'height'=>'100px',
		'resize_enabled'=> false,
	)
);
$configcke2 = array(
	'config'=>array(
		'toolbar' => array(
		    array( 'Source', '-', 'Bold', 'Italic', 'Underline', 'Strike' ),
		    array( 'Image', 'Link', 'Unlink', 'Anchor' )
		),
		'toolbarStartupExpanded'=> false
	)
);
?><?if($this->getIdToEdit()):?>
<input type="hidden" name="resultado_esperado[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo ResultadoEsperado');
	else:
		echo $this->__t('Editar ResultadoEsperado');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de ResultadoEsperado</h3>
		<div>
			<label>Objetivo: </label>
			<span><?
				//echo c($selector_tipo_objetivo = $this->appendBlock('<selector_objetivo />'))
				echo c($selector_tipo_objetivo = $this->appendBlock('<selector_objetivo_simple />'))
					->setSelectedValue($x->getIdObjetivo())
					->void($selector_tipo_objetivo
						->getSelectControl()
							->setName('resultado_esperado[id_objetivo]')
							->setId('id_objetivo')
							->setData('data-campo', '<b>Objetivo</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
				if($ore_renderer = $this->getChild('objetivo_listado_re_renderer')){
					if($objetivos = $selector_tipo_objetivo->getAllOptions()){
						foreach($objetivos as $objetivo){
							$ore_renderer->setObjetivo($objetivo);
							echo $ore_renderer->toHtml();
						}
					}
				}
			if(false):
				$objetivo = new Inta_Model_Objetivo();
				$objetivos = $objetivo->search();
				$html_select = '';
				foreach($objetivos as $objetivo){
					$option = c(Core::getObject('Core_Html_Tag_Custom', 'option'))
						->setValue($objetivo->getId())
						->setInnerHtml($objetivo->getNombre())
					;
					if($objetivo->getId()==$x->getIdObjetivo())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(Core::getObject('Core_Html_Tag_Custom', 'select'))
					->setName('resultado_esperado[id_objetivo]')
					->setId('id_objetivo')
					//->setDisabled('disabled')
					->setInnerHtml($html_select)
					->getHtml()
				;
			endif;
			?> 
			</span>
			<label>Descripcion: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setMaxlength(300)
					->setType('textarea')
					->setId('descripcion')
					->setRows(5)
					->setCols(30)
					->setName('resultado_esperado[descripcion]')
					->setInnerHtml(htmlentities(stripslashes($x->getDescripcion())))
					->setData('data-campo', '<b>Descripcion</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
				
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<?php print $this->getChildHtml('hijos_abajo'); ?>
	<div class="controls">
		<?php if(in_array('entity_new',$this->getLayout()->getActions())): ?> 
		<input type="submit" id="guardar" value="<?php print $this->__t('Guardar y Cargar Indicadores'); ?>"/>
		<?php else: ?> 
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setId('guardar')->setValue('Guardar')->getHtml(); ?>
		<?php endif; ?>
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('hidden')->setName('crear_nuevo')->setValue('0')->getHtml(); ?>
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('button')->setId('continuar')->setValue($this->__t('Guardar y crear nuevo'))->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){
	jQuery('#descripcion').ckeditor(<?php print json_encode($configcke1); ?>);
	jQuery('#id_objetivo').change(function(){
		var jqform = jQuery(this).parents('form:first');
		jqform.find('.listado_re').hide();
		if(this.value!='')
			jqform.find('.listado_re_'+this.value).show();
	}).change();
	jQuery('#continuar').click(function(){
		var jqform = jQuery(this).parents('form:first');
		jqform.find('[name=crear_nuevo]').val(1);
		jqform.submit();
	});
	jQuery('#guardar').click(function(){
		var jqform = jQuery(this).parents('form:first');
		jqform.find('[name=crear_nuevo]').val(0);
		//jqform.submit();//ya es submit este
	});
});


function validar_agregar_resultado_esperado_datos(formData, jqForm, options) {
	jQuery('#descripcion').ckeditor('refresh');
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>