<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?>
<div id="<?php print $id_control = $this->generateRandomId(); ?>" class="listado_indicadores_resultado_esperado">
<?if($this->getIdToEdit()):?>
<input type="hidden" name="resultado_esperado[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?php print $this->__t('Indicadores de ResultadoEsperado'); ?></legend>
	<fieldset>
		<div>
				<div class="indicadores_resultado"><?
					//if(!($indicadores = $x->getIndicadores())){
					if(!($indicadores = $x->getListIndicador())){
						echo '<div class="fila">'.$fila_indicador.'</div>';
					}
					else{
						$block_vista_indicador = $this->getChild('ver_indicador_resultado_esperado');
						echo '<ul class="indicadores_resultado">';
						foreach($indicadores as $indicador_resultado){
							$block_vista_indicador->setObjectToEdit($indicador_resultado);
							echo $block_vista_indicador->toHtml();
						}
						echo '</ul>';
					}
				?>
				</div> 
			<br />
			<div style="height:auto;width:auto;" class="btn_agregar btn_agregar_indicador">Agregar Indicador</div>
		</div>
	</fieldset>
	<?/** /?>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
	<?/**/?>
</fieldset>
<script>
jQuery(document).ready(function(){
	//jQuery('#descripcion').ckeditor();
	var jqform = jQuery('#<?php print $id_fielset; ?>');
	jQuery('.btn_agregar_indicador', jqform)
		.css('cursor','pointer')
		.click(function(){
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'<?php print 'administrator/ajax/resultado_esperado/addEditIndicador/'.$x->getId().'/'; ?>',
				{
					//target: '#'+jQuery('#<?php print $id_control; ?>').parents('.ui-tabs-panel:first').attr('id')
					//t arget: '#'+jQuery('#<?php print $id_control; ?>').parents('.listado_indicadores_resultado_esperado:last').attr('id')
					target: '#'+jQuery(this).parents('.listado_indicadores_resultado_esperado:last').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			);
		})
	;
	jQuery('.btn_eliminar_indicador', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFDDDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var that = this;
			var jqthat = jQuery(this);
			var jqwin = jQuery('<div></div>');
			jqwin.html('&iquest;Desea continuar eliminando el indicador y sus medios de verificacion asociados?<br />');
			var jqaceptar = jQuery('<input type="button" value="Continuar" />')
				.click(function(){
					var id_indicador_resultado = jqthat.parents('li:first').attr('data-id');
					var jqwait = jQuery('<div></div>');
					jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
					jqwait.ScreenBlock();
					jQuery.get(
						'administrator/ajax/resultado_esperado/deleteIndicador/'+id_indicador_resultado+'/',
						function (data){
							jQuery.ScreenBlock(false);
							//jQuery('#<?php print $id_control; ?>')
							jQuery(that)
								//.parents('.ui-tabs-panel:first')
								.parents('.listado_indicadores_resultado_esperado:last')
								.html(data)
							;
						}
					)
				})
				.appendTo(jqwin)
			;
			var jqcancelar = jQuery('<input type="button" value="Cancelar" />')
				.click(function(){
					jQuery.ScreenBlock(false);
				})
				.appendTo(jqwin)
			;
			jqwin.ScreenBlock();
		})
	;
	jQuery('.btn_editar_indicador', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFFFBB')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var id_indicador_resultado = jqthat.parents('li:first').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'<?php print 'administrator/ajax/resultado_esperado/addEditIndicador/'.$x->getId().'/'; ?>'+id_indicador_resultado,
				{
					target: '#'+jQuery(this).parents('.listado_indicadores_resultado_esperado:last').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			)
		})
	;
	jQuery('.btn_agregar_medio_verificacion', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#DDFFDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var id_indicador_resultado = jqthat.parents('li:first').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'administrator/ajax/resultado_esperado/addEditMedioVerificacion/'+id_indicador_resultado+'/',
				{
					target: '#'+jQuery(this).parents('.listado_indicadores_resultado_esperado:last').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			);
		})
	;
	jQuery('.btn_eliminar_medio_verificacion', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFDDDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var that = this;
			var jqthat = jQuery(this);
			var jqwin = jQuery('<div></div>');
			jqwin.html('&iquest;Desea continuar eliminando el medio de verificaci&oacute;n?<br />');
			var jqaceptar = jQuery('<input type="button" value="Continuar" />')
				.click(function(){
					var id_medio_verificacion_indicador_resultado = jqthat.parents('li:first').attr('data-id');
					var jqwait = jQuery('<div></div>');
					jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
					jqwait.ScreenBlock();
					jQuery.get(
						'administrator/ajax/resultado_esperado/deleteMedioVerificacion/'+id_medio_verificacion_indicador_resultado+'/',
						function (data){
							jQuery.ScreenBlock(false);
							//jQuery('#<?php print $id_control; ?>')
							jQuery(that)
								//.parents('.ui-tabs-panel:first')
								.parents('.listado_indicadores_resultado_esperado:last')
								.html(data)
							;
						}
					)
				})
				.appendTo(jqwin)
			;
			var jqcancelar = jQuery('<input type="button" value="Cancelar" />')
				.click(function(){
					jQuery.ScreenBlock(false);
				})
				.appendTo(jqwin)
			;
			jqwin.ScreenBlock();
		})
	;
	jQuery('.btn_editar_medio_verificacion', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#FFFFBB')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var id_indicador_resultado = jqthat.parents('li:eq(1)').attr('data-id');
			var id_medio_verificacion_indicador_resultado = jqthat.parents('li:eq(0)').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'<?php print 'administrator/ajax/resultado_esperado/addEditMedioVerificacion/'; ?>'+id_indicador_resultado+'/'+id_medio_verificacion_indicador_resultado,
				{
					target: '#'+jQuery(this).parents('.listado_indicadores_resultado_esperado:last').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			)
		})
	;
	jQuery('.btn_agregar_indicador_attach', jqform)
		.css('cursor','pointer')
		.mouseover(function(){
			jQuery(this).parents('li:first').css('background-color','#DDFFDD')
		})
		.mouseout(function(){
			jQuery(this).parents('li:first').css('background-color','')
		})
		.click(function(){
			var jqthat = jQuery(this);
			var id_medio_verificacion_indicador_resultado = jqthat.parents('li:first').attr('data-id');
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'administrator/ajax/documento/addEdit/medio_verificacion_indicador_resultado/'+id_medio_verificacion_indicador_resultado+'/',
				{
					target: '#'+jQuery(this).parents('.listado_indicadores_resultado_esperado:last').attr('id')+' .medios_verificacion_indicador_resultado>li[data-id='+id_medio_verificacion_indicador_resultado+'] .listado_documentos'
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			);
		})
	;

});

function validar_agregar_resultado_esperado_indicadores(formData, jqForm, options) {
	
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>
</div>