<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$configcke1 = array(
	'config'=>array(
		'toolbar' => 'Basic',
		'toolbarStartupExpanded'=> false,
	)
);
$configcke2 = array(
	'config'=>array(
		'toolbar' => array(
		    array( 'Source', '-', 'Bold', 'Italic', 'Underline', 'Strike' ),
		    array( 'Image', 'Link', 'Unlink', 'Anchor' )
		),
		'toolbarStartupExpanded'=> false
	)
);

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()||!$x->getEstado()||$x->getEstado()=='planificado'):
		echo $this->__t('Planificar Actividad');
	else:
		echo $this->__t('Seguimiento de Actividad');
	endif;?></legend>
	<?php print $this->getChildHtml('hijos_arriba'); ?>
	<fieldset>
		<h3><?php print $this->__t('Informacion de Actividad'); ?></h3>
		<div>
			<label for="nombre"><?
				if(Admin_Actividad_Helper::canEditNombre($x)){
					echo 'Nombre: ';
					$input = Core::getObject('Core_Html_Tag_Custom', 'input');
					$input
						->setMaxlength(300)
						->setType('text')
						->setId('nombre')
						->setSize(50)
						->setName('actividad[nombre]')
						->setValue($x->getNombre())
						->setData('data-campo', '<b>Nombre</b>')
						->setData('data-validator', '{empty:false}')
					;
					echo $input->getHtml();
				}
				else{
					echo '<h4>'.$x->getNombre().'</h4>';
				}
			?></label>
			<table>
				<tr>
					<td>
						<label><?
						if(Admin_Actividad_Helper::canEditAno($x)){
							echo 'A&ntilde;o: ';
							$input = Core::getObject('Core_Html_Tag_Custom', 'input');
							if(!$x->getAno()){
								$x->setAno(date('Y'));
							}
							$input
								->setMaxlength(4)
								->setType('text')
								->setId('ano')
								->setReadonly('readonly')
								//->setName('actividad[ano]')
								->setValue($x->getAno())
								->setData('data-campo', '<b>Año</b>')
								->setData('data-validator', '{empty:false,entero:4}')
								->setSize(4)
							;
							echo $input->getHtml();
						}
						else{
							echo 'A&ntilde;o '.$x->getAno().' -';
						}
						?></label>
			            
					</td>
					<td style="padding-left:10px">
						<label><?
							if(Admin_Actividad_Helper::canEditIdResponsable($x)){
								echo 'Responsable: ';
								echo c($selector_usuario = $this->appendBlock('<selector_usuario />'))
									->setSelectedValue($x->getIdResponsable())
									->void($selector_usuario
										->getSelectControl()
											->setName('actividad[id_responsable]')
											->setId('id_responsable')
											->setData('data-campo', '<b>Responsable</b>')
											->setData('data-mensaje', 'Seleccione %field')
											->setData('data-validator', '{empty:false}')
									)
									->toHtml()
								;
							}
							else{
								$responsable = Admin_Actividad_Helper::getResponsable($x);
								echo 'Responsable: '.($responsable->getApellido()).', '.($responsable->getNombre()); 
							}
						?></label>
					</td>
				</tr>
			</table>
			<?php if(Admin_Actividad_Helper::canEditPorcentajeCumplimiento($x)): ?> 
			<label>Porcentaje Cumplimiento: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('porcentaje_cumplimiento')
					->setReadonly('readonly')
					->setName('actividad[porcentaje_cumplimiento]')
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setValue($x->getPorcentajeCumplimiento())
					->setData('data-campo', '<b>Porcentaje Cumplimiento</b>')
					->setData('data-validator', '{empty:false,porcentaje:true}')
				;
				echo $input->getHtml();
			?></label>
			<span>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#porcentaje_cumplimiento', 'min'=>0,'max'=>100, 'step'=>10, 'fixed'=>2, 'value_sufix'=>' %'))); ?>"></div>
			</span>
			<?php endif; ?>
			<label>Porcentaje Tiempo Anual: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('porcentaje_tiempo')
					->setReadonly('readonly')
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setValue($x->getPorcentajeTiempo())
					->setData('data-campo', '<b>Porcentaje Tiempo</b>')
					->setData('data-validator', '{empty:false,porcentaje:true}')
				;
				if(Admin_Actividad_Helper::canEditPorcentajeTiempo($x)){
					$input
						->setName('actividad[porcentaje_tiempo]');
				}
				echo $input->getHtml();
			?></label>
			<?php if(Admin_Actividad_Helper::canEditPorcentajeTiempo($x)): ?> 
			<span>
				<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#porcentaje_tiempo', 'min'=>0,'max'=>100, 'step'=>10, 'fixed'=>2, 'value_sufix'=>' %'))); ?>"></div>
			</span>
			<?php endif; ?> 
			<?php if(false): /*esta deprecated este campo, el listao de proyectos lo contempla*/?> 
			<label for="presupuesto_estimado">Presupuesto Estimado: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('presupuesto_estimado')
					->setStyle('border: 0pt none; color: rgb(147,190, 31); font-weight: bold;')
					->setValue($x->getPresupuestoEstimado())
					->setData('data-campo', '<b>Presupuesto Estimado</b>')
					->setData('data-validator', '{empty:false,decimal:2}')
				;
				if(Admin_Actividad_Helper::canEditPresupuestoEstimado($x)){
					$input
						->setName('actividad[presupuesto_estimado]');
				}
				else{
					$input->setReadonly('readonly');
				}
				echo $input->getHtml();
			?></label>
			<?php endif; ?>
			<label for="estado">Estado: <?
					$aOptionsEstados = $aOptions = Admin_Actividad_Helper::getOpcionesEstadosPosiblesDeCambio($x);
					if(true){
						$estado = $x->getEstado();
						if(!$estado)
							$estado = array_pop(array_slice(array_keys($aOptionsEstados), 0, 1));
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setType('hidden')
							->setId('estado')
							->setName('actividad[estado]')
							->setValue($estado)
						;
						echo $input->getHtml();
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setType('hidden')
							->setId('motivo_atrasado')
							->setName('actividad[motivo_atrasado]')
							->setValue($x->getMotivoAtrasado())
						;
						echo $input->getHtml();
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setType('hidden')
							->setId('motivo_cancelado')
							->setName('actividad[motivo_cancelado]')
							->setValue($x->getMotivoCancelado())
						;
						echo $input->getHtml();
						
						while(true){
							if($x->getEstado()){
								$estado = $x->getEstado();
								if(isset($aOptionsEstados[$estado])){
									echo $aOptionsEstados[$estado];
									break;
								}
							}
							echo array_pop(array_slice($aOptionsEstados, 0, 1));
							break;
						}
					}
					else{
						$select = Core::getObject('Core_Html_Tag_Custom', 'select');
						$select
							->setId('estado')
							->setName('actividad[estado]')	
						;
						$html = '';
						$aOptionsEstados = $aOptions = Admin_Actividad_Helper::getOpcionesEstadosPosiblesDeCambio($x);
						foreach($aOptions As $key => $value){
							$option = Core::getObject('Core_Html_Tag_Custom', 'option');
							$option
								->setValue($key)
								->setInnerHtml($value)
							;
							if($x->getEstado()==$key)
								$option->setSelected('selected');
							$html .= $option->getHtml();
						}
						$select->setInnerHtml($html);
                        echo $select->getHtml();
                    }
				
			?></label>
			<?php if(Admin_Actividad_Helper::canViewMotivoAtrasado($x)): ?> 
				<label>Motivo de atraso:</label>
				<div class="motivo"><?php print nl2br(htmlentities($x->getMotivoAtrasado())); ?></div> 
			<?php endif; ?> 
			<?php if(Admin_Actividad_Helper::canViewMotivoCancelado($x)): ?> 
				<label>Motivo de cancelaci&oacute;n:</label>
				<div class="motivo"><?php print nl2br(htmlentities($x->getMotivoCancelado())); ?></div>
			<?php endif; ?> 
		</div>
	</fieldset>
	<fieldset>
		<h3>Informacion de Actividad</h3>
		<div>
			<label>Observaciones: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setId('observaciones')
					->setName('actividad[observaciones]')
					->setInnerHtml(htmlentities($x->getObservaciones()))
                                        ->setRows(5)
                                        ->setCols(40)
//					->setData('data-campo', '<b>Observaciones</b>')
//					->setData('data-validator', '{empty:false}')
//                                        ->setData('data-mensaje', 'Debe cargar uno o mas %field separados por comas')
				;
				echo $input->getHtml();
			?>
			</span><?{/** /?> 
			<label>Comentarios: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setId('comentario')
					->setName('actividad[comentario]')
					->setInnerHtml(htmlentities($x->getComentario()))
                                        ->setRows(5)
                                        ->setCols(40)
//					->setData('data-campo', '<b>Comentarios</b>')
//					->setData('data-validator', '{empty:false}')
//                                        ->setData('data-mensaje', 'Debe cargar uno o mas %field separados por comas')
				;
				echo $input->getHtml();
			?>
			</span><?/**/}?>
		</div>
	</fieldset>
	<?php print $this->getChildHtml('hijos_abajo'); ?>
	<div class="controls">
		<?php
		foreach($aOptionsEstados as $estado=>$nombre_estado){
			if($estado==$x->getEstado())
				continue;
			print Core::getObject('Core_Html_Tag_Custom', 'input')
				->settype('button')
				->setData('data-cambia-estado',json_encode(array('estado'=>$estado, 'nombre_estado'=>$nombre_estado)))
				->setValue('Guardar como "'.$nombre_estado.'"')
				->getHtml()
			; 
		}?> 
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>
jQuery(document).ready(function(){
	var form_id = <?php print json_encode($id_fielset); ?>;
	jQuery('[data-cambia-estado]').click(function(){
		var jqform = jQuery(this).parents('form:first');
		var opciones = jQuery(this).attr('data-cambia-estado');
		try{
			eval('opciones='+opciones);
		}catch(e){
			return;
		}
		var jqwindow = jQuery('<div class="pregunta"></div>');
		jqwindow.html('¿Desea continuar cambiando el estado de la actividad a <b>'+opciones.nombre_estado+'</b>?');
		var jqmotivo = jQuery('#'+form_id+' #motivo_'+opciones.estado);
		if(jqmotivo.length){
			jqwindow.append('<div>Motivo:<textarea id="motivoingresado" rows="5" cols="50"></textarea></div>');
		}
		jqwindow.append('<div><input type="button" value="continuar" /></div>');
		jqwindow.find('input').css('cursor','pointer').click(function(){
			if(jqmotivo.length){
				var jqmotivoingresado = jQuery(this).parents('.pregunta').find('textarea');
				if(jqmotivoingresado.length){
					jqmotivo.val(jqmotivoingresado.val());
				}
			}
			jQuery('#'+form_id+' #estado').val(opciones.estado);
			jQuery.ScreenBlock(false);
			jqform.submit();
		});
		jqwindow.ScreenBlock();
	});
	jQuery('#observaciones').ckeditor(<?php print json_encode( $configcke1 ); ?>);
	jQuery('#comentario').ckeditor(<?php print json_encode($configcke1); ?>);
    jQuery('input[type=button][value=Agregar]').live('click',function(){
//        jQuery(this).parents('div').eq(0).clone().appendTo(jQuery(this).parents('fieldset').eq(0));
        var x = jQuery(this).parents('div').eq(0).clone();
        jQuery(x).appendTo(jQuery(this).parents('fieldset').eq(0));
        jQuery('input[type=button][value=Eliminar]',x).css('display','inline');
    });
    jQuery('input[type=button][value=Eliminar]').live('click',function(){
        jQuery(this).parents('div').eq(0).remove();
    });
    jQuery('.slider').each(function(){
    	jQuery(this).css('margin-top', '9px');
		var data = jQuery(this).attr('data-info');
		var options = null;
		try{
			eval('options='+data);
		}
		catch(e){
			alert("kradkk");
			return;
		}
		options.value = jQuery(options.target).val();
		options.slide = function(event, ui){
			var val = ui.value;
			if(options.fixed){
				val = (new Number(parseFloat(val))).toFixed(options.fixed);
			}
			if(options.value_sufix)
				val += options.value_sufix;
			jQuery(options.target).val(val);
		}
		jQuery(this).slider(options);
		var valor = jQuery(options.target).val();//esto es para actualizar la visualización en la edición cuando se carga el form
		valor = parseInt(valor);
		valor = isNaN(valor)?0:valor;
		options.slide(null, {value:valor});
		//jQuery(options.target).val(ui.value);
	})
	//$("#amount").val('$' + $("#slider").slider("value"));

});
function validar_agregar_actividad(formData, jqForm, options) {
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		return false;
	}
	return(true);
}
</script>