<?php
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):
        $actividad_proyecto = new Inta_Model_ActividadProyecto();
        $aActividadProyecto = $actividad_proyecto->search(null,'ASC',null,0,'Inta_Model_ActividadProyecto');
?>
<input type="hidden" name="actividad[id_proyecto]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Proyecto');
	else:
		echo $this->__t('Editar Proyecto');
	endif;?></legend>
	<fieldset>
		<h3>Datos</h3>
<?php
    $contador = 0;
    if($aActividadProyecto)
    foreach($aActividadProyecto As $oActividadProyecto){
?>
		<div>
			<label>Nombre: </label>
			<span><?
                                $select = Core::getObject('Core_Html_Tag_Custom', 'select');
                                $select
                                        ->setId('id_proyecto')
                                        ->setName('actividad_proyecto[id_proyecto][]')
                                ;
                                $html = '';
                                $i = new Inta_Model_Proyecto();
                                $a = $i->search();
                                if(!empty($a))
					foreach($a as $o){
						$option = Core::getObject('Core_Html_Tag_Custom', 'option');
						$option
							->setValue($o->getId())
							->setInnerHtml($o->getNombre())
						;
						if($o->getId()==$oActividadProyecto->getIdProyecto())
							$option->setSelected('selected');
						$html .= $option->getHtml();
					}
				echo $select
					->setInnerHtml($html)
					->getHtml()
				;
			?>
			</span>
                        <label>Monto: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setSize('10')
					->setId('monto_proyecto')
					->setName('actividad_proyecto[monto_proyecto][]')
					->setValue($oActividadProyecto->getMonto())
					->setData('data-campo', '<b>Monto</b>')
//					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?>
			</span>
                        <span><?
                            $input = Core::getObject('Core_Html_Tag_Custom', 'input');
                            $input
                                    ->setType('button')
                                    ->setValue('Agregar')
                            ;
                            echo $input->getHtml();
                            $input
                                    ->setType('button')
                                    ->setValue('Eliminar')
                                    ->setStyle($contador==0?'display:none':'display:inline')
                            ;
                            echo $input->getHtml();
                        ?>
                        </span>
		</div>
<?php
    $contador++;
    }
?>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>
function validar_agregar_proyecto(formData, jqForm, options) {
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		return false;
	}
	return(true);
}
</script>