<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<?php if(!$this->getNofieldset()): ?> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Actividad');
	else:
		echo $this->__t('Editar Actividad');
	endif;?></legend>
<?php endif; ?> 
	<fieldset>
            <h3>Cronograma de Planeaci&oacute;n</h3>
            <div><ul class="cronograma_actividad"><?php
            $meses = array(
            	array(
            		'name'=>'mes_enero',
            		'label'=>'Enero',
				),
            	array(
            		'name'=>'mes_febrero',
            		'label'=>'Febrero',
				),
            	array(
            		'name'=>'mes_marzo',
            		'label'=>'Marzo',
				),
            	array(
            		'name'=>'mes_abril',
            		'label'=>'Abril',
				),
            	array(
            		'name'=>'mes_mayo',
            		'label'=>'Mayo',
				),
            	array(
            		'name'=>'mes_junio',
            		'label'=>'Junio',
				),
            	array(
            		'name'=>'mes_julio',
            		'label'=>'Julio',
				),
            	array(
            		'name'=>'mes_agosto',
            		'label'=>'Agosto',
				),
            	array(
            		'name'=>'mes_septiembre',
            		'label'=>'Septiembre',
				),
            	array(
            		'name'=>'mes_octubre',
            		'label'=>'Octubre',
				),
            	array(
            		'name'=>'mes_noviembre',
            		'label'=>'Noviembre',
				),
            	array(
            		'name'=>'mes_diciembre',
            		'label'=>'Diciembre',
				),
			);
			foreach($meses as $data){
				$mes = new Core_Object($data);
				$checked = $x->getData($mes->getName());
				?> 
				<li class="<?php print $checked?'activo':''?>">
				<span> 
                    <?
//                            $input = Core::getObject('Core_Html_Tag_Custom', 'input');
//                            $input
//                                    ->setType('checkbox')
//                                    ->setId('mes_enero')
//                                    ->setName('actividad[mes_enero]')
//                                    ->setValue(1)
//                            ;
//                            if($x->getMesEnero())
//                                $input->setChecked($x->getMesEnero('on'));
//                            echo $input->getHtml();
                            if(Admin_Actividad_Helper::canEditCronograma($x)){
								echo c($input = Core::getObject('Core_Html_Tag_Custom', 'input'))
									->setType('hidden')
									->setName('actividad['.$mes->getName().']')
									->setValue('0')
									->getHtml();
								if($checked){
									$input->setChecked('checked');
								}
								echo $input
									->setType('checkbox')
									->setId($mes->getName())
									->setValue('1')
									->getHtml()
								;
							}
                    ?></span>
                    <label for="<?php print $mes->getName(); ?>"><?php print $mes->getLabel(); ?></label>
                    <div style="clear:both;"></div>
                    </li>
                    <?php
				}?> 
            </ul></div>
	</fieldset>
<?php if(!$this->getNofieldset()): ?> 
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<?php endif; ?> 
<script>

jQuery(document).ready(function(){
	jQuery('.cronograma_actividad li input').change(function(){
		if(this.checked)
			jQuery(this).parents('li:first').addClass('activo')
		else
			jQuery(this).parents('li:first').removeClass('activo')
	});
//    jQuery('input[type=submit]').unbind('click');
//    $('input[type=submit]').bind('click', function() {
//      //jQuery('input[type=checkbox][#^=mes]:not(:checked)').val(0).attr('checked','true');
//    });
})
</script>