<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="usuario[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Usuario');
	else:
		echo $this->__t('Editar Usuario');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de Usuario</h3>
		<table style="width:100%;">
			<colgroup>
				<col width="1" />
				<col width="" />
				<col width="1" />
				<col width="" />
			</colgroup>
			<tr>
				<td>
					<label>Activo</label>
				</td>
				<td>
					<span>
						<span class="select_container">
							<select name="usuario[activo]" id="activo">
								<option value="si">Si</option>
								<option value="no"<?php print ($x->getActivo()=='no'?' selected="selected"':''); ?>>No</option>
							</select>
						</span>
					</span>
				</td>
				<td>
					<label>Telefono</label>
				</td>
				<td>
					<span>
					<?
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setMaxlength(300)
							->setType('text')
							->setId('nombre')
							->setName('usuario[telefono]')
							->setValue($x->getTelefono())
//							->setData('data-campo', '<b>Telefono</b>')
//							->setData('data-validator', '{empty:false}')
						;
						echo $input->getHtml();
					?>
					</span>
				</td>
			</tr>
			<tr>
				<td>
					<label>Nombre: </label>
				</td>
				<td>
					<span><?
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setMaxlength(300)
							->setType('text')
							->setId('nombre')
							->setName('usuario[nombre]')
							->setValue($x->getNombre())
							->setData('data-campo', '<b>Nombre</b>')
							->setData('data-validator', '{empty:false}')
						;
						echo $input->getHtml();
					?>
					</span>
				</td>
				<td>
					<label>Apellido: </label>
				</td>
				<td>
					<span><?
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setMaxlength(300)
							->setType('text')
							->setId('apellido')
							->setName('usuario[apellido]')
							->setValue($x->getApellido())
							->setData('data-campo', '<b>Apellido</b>')
							->setData('data-validator', '{empty:false}')
						;
						echo $input->getHtml();
					?>
					</span>
				</td>
			</tr>
			<tr>
				<td>
					<label>Email: </label>
				</td>
				<td>
					<span><?
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setMaxlength(300)
							->setType('text')
							->setId('email')
							->setName('usuario[email]')
							->setValue($x->getData('email'))
							->setData('data-campo', '<b>Email</b>')
							->setData('data-validator', '{empty:false}')
						;
						echo $input->getHtml();
					?>
					</span>
				</td>
				<td>
					<label>Username: </label>
				</td>
				<td>
					<span><?
						$input = Core::getObject('Core_Html_Tag_Custom', 'input');
						$input
							->setMaxlength(300)
							->setType('text')
							->setId('username')
							->setName('usuario[username]')
							->setValue($x->getData('username'))
							->setData('data-campo', '<b>Username</b>')
							->setData('data-validator', '{empty:false}')
						;
						echo $input->getHtml();
					?>
					</span>
				</td>
			</tr>
			<tr>
				<td>
				</td>
				<td>
				</td>
				<td>
				</td>
				<td>
				</td>
			</tr>
		</table>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){

})
function validar_agregar_usuario(formData, jqForm, options) {
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		return false;
	}
	return(true);
}
</script>