<table id="list1" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager1" class="scroll" style="text-align:center;"></div> 
<script>
jQuery("#list1").jqGrid({
   	url:'<?=$this->getUrl($this->getSource())?>?q=1',
	datatype: "xml",
   	colNames:['Inv No','Date', 'Client', 'Amount','Tax','Total','Notes'],
   	colModel:[
   		{name:'id',index:'id', width:55},
   		{name:'invdate',index:'invdate', width:200},
   		{name:'name',index:'name', width:100},
   		{name:'amount',index:'amount', width:80, align:"right"},
   		{name:'tax',index:'tax', width:80, align:"right"},		
   		{name:'total',index:'total', width:80,align:"right"},		
   		{name:'note',index:'note', width:150, sortable:false}		
   	],
   	rowNum:10,
   	rowList:[10,20,30],
   	imgpath: '<?=$this->getSkinUrl('jqGrid/themes/basic/images')?>',
   	pager: jQuery('#pager1'),
   	sortname: 'id',
    viewrecords: true,
    sortorder: "desc",
    caption:"XML Example",
    editurl:"someurl.php"
}).navGrid('#pager1',{edit:false,add:false,del:false}); 
</script> 