<?php  //es útf8

$mascotas = $this->getMascotas();

?>

<?php if(!isset($mascotas)||!count($mascotas)): ?> 
<h3>No hay mascotas Reportadas como Perdidas</h3>
<?php return; endif; ?> 

<?php $filled_width=0;$fill_width = $this->getFillWidth() ?>
<ul class="random_mascotas random_perdida">
<?php foreach($mascotas as $mascota): ?>
	<?php
	if($fill_width){
		list($width, $height) = $mascota->getSizeImage(0, 100);
		
		if(($filled_width+$width)>$fill_width)
			continue;
		$filled_width += $width;
	}
	?>
	<li>
		<a href="<?php print $this->getUrl($mascota->getUrlListadoPerdida()); ?>">
			<img src="<?php print $mascota->getUrlImage(0, 100); ?>" title="Mascota Perdida: <?php print htmlentities(utf8_encode($mascota->getNombre())); ?>" />
		</a>
	</li>
<?php endforeach; ?>
<?php if($fill_width): ?>
	<li style="display: inline-block; width: <?php print $fill_width.'px'; ?>;"></li>
<?php endif; ?> 
</ul>
<ul class="multilink">
	<li>
		<a href="<?php print $this->getUrl(Frontend_Mascota_Perdida_Helper::getUrlAgregar()); ?>">Perdí mi mascota</a>
	</li>
	<li>
		<a href="<?php print $this->getUrl(Frontend_Mascota_Perdida_Listado_Helper::getUrl()); ?>">Ver todas las mascotas perdidas</a>
	</li>
</ul>