<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


?><?if($this->getIdToEdit()):?>
<input type="hidden" name="usuario_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="usuario_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo UsuarioActividad');
	else:
		echo $this->__t('Editar UsuarioActividad');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de UsuarioActividad</h3>
		<div>
			<label>Usuario: </label>
			<span><?
				echo c($selector_usuario = $this->appendBlock('<selector_usuario />'))
					->setSelectedValue($x->getIdUsuario())
					->void($selector_usuario
						->getSelectControl()
							->setName('usuario_actividad[id_usuario]')
							->setId('id_usuario')
							->setData('data-campo', '<b>Usuario</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

function usuario_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_usuario_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>