<div> 
		<div class="canhide message_box message_info">No hay resultados resultados de busqueda</div> 
</div>
<div style="margin:0 20px">
	<p>Para agregar resultados a la b&uacute;squeda puede hacerlo
	<ul>
		<li>Mediante una b&uacute;squeda en el men&uacute; Reporte&gt;<a href="#reporte/addEdit">Agregar por b&uacute;squeda</a>. <a target="_blank" href="<?php print $this->getSkinUrl('inta/videos/inta_agregar_por_busqueda.swf'); ?>#">Ver ejemplo</a></li>
		<li>Manualmente eligiendo actividades de los listados de actividaes en Actividad&gt;<a href="#actividad/listar_planificadas">Planificadas</a>, Actividad&gt;<a href="#actividad/listar_iniciadas">Seguimiento</a> o Actividad&gt;<a href="#actividad/listar">Ver Todas</a>. <a target="_blank" href="<?php print $this->getSkinUrl('inta/videos/inta_agregar_reporte_manual.swf'); ?>#">Ver ejemplo</a></li>
	</ul> 
	</p>
</div>