<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="medio_verificacion_indicador_resultado[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="medio_verificacion_indicador_resultado[id_indicador_resultado]" value="<?=$x->getIdIndicadorResultado()?>" />
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> MedioVerificacionIndicadorResultado</legend>
	<fieldset>
		<div><?php
				if($indicador_resultado = $x->getIndicadorResultado()){
					echo 'Indicador: <b>'.$indicador_resultado->getDescripcion().'</b>';
				}
		?> 
			<label>Medio de Verificaci&oacute;n: </label>
			<span><?
				
//				$medio_verificacion = new Inta_Model_MedioVerificacion();
//				if($indicador_resultado = $x->getIndicadorResultado()){
//					$medio_verificacion
//						->setIdIndicador($indicador_resultado->getIdIndicador())
//						->setWhere(Db_Helper::equal('id_indicador'))
//					;
//				}
//				$medio_verificacions = $medio_verificacion->search();
//				$html_select = '';
//				foreach($medio_verificacions as $medio_verificacion){
//					$option = c(Core::getObject('Core_Html_Tag_Custom', 'option'))
//						->setValue($medio_verificacion->getId())
//						->setInnerHtml($medio_verificacion->getNombre())
//					;
//					if($medio_verificacion->getId()==$x->getIdMedioVerificacion())
//						$option->setSelected('selected');
//					$html_select .= $option->getHtml();
//				}
//				echo c(Core::getObject('Core_Html_Tag_Custom', 'select'))
//					->setName('medio_verificacion_indicador_resultado[id_medio_verificacion]')
//					->setId('id_medio_verificacion')
//					//->setDisabled('disabled')
//					->setInnerHtml($html_select)
//					->getHtml()
//				;
				
//				echo c($selector_audiencia = $this->appendBlock('<selector_medio_verificacion />'))
//					->setSelectedValue($x->getIdMedioVerificacion())
//					->setData('id_indicador', $indicador_resultado->getIdIndicador())
//					->void($selector_audiencia
//						->getSelectControl()
//							->setName('medio_verificacion_indicador_resultado[id_medio_verificacion]')
//							->setId('id_medio_verificacion')
//							->setData('data-campo', '<b>Medio Verificacion</b>')
//							->setData('data-mensaje', 'Seleccione %field')
//							->setData('data-validator', '{empty:false}')
//					)
//					->toHtml()
//				;

				echo c($selector_audiencia = $this->appendBlock('<selector_medio_verificacion_abm />'))
					->setSelectedValue($x->getIdMedioVerificacion())
					->setData('id_indicador', $indicador_resultado->getIdIndicador())
					->void($selector_audiencia
						->getSelectControl()
							->setName('medio_verificacion_indicador_resultado[id_medio_verificacion]')
							->setId('id_medio_verificacion')
							->setData('data-campo', '<b>Medio Verificacion</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
			?> 
			</span>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script type="text/javascript">
function medio_verificacion_indicador_resultado_enviado(responseText, statusText, xhr, $form){
	//window.console.log({resultado:responseText});<?php 
	if(false&&$this->hasTargetContainer()){?> 
	jQuery('<?php print $this->getTargetContainer(); ?>').html(responseText);<?
	}?> 
	jQuery.ScreenBlock(false);
}
function validar_agregar_medio_verificacion_indicador_resultado_datos(){
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	var jqwait = jQuery('<div></div>');
	jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
	jqwait.ScreenBlock();

}
</script>