<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="agencia[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Agencia');
	else:
		echo $this->__t('Editar Agencia');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de Agencia</h3>
		<div>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('agencia[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Direcci&oacute;n: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('direccion')
					->setName('agencia[direccion]')
					->setValue($x->getDireccion())
					->setData('data-campo', '<b>Direcci&oacute;n</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<fieldset>
		<h3>Datos de contacto</h3>
		<div>
			<label>Telefono: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('telefono')
					->setName('agencia[telefono]')
					->setValue($x->getTelefono())
					->setData('data-campo', '<b>Telefono</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Email: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('email')
					->setName('agencia[email]')
					->setValue($x->getEmail())
					->setData('data-campo', '<b>Email</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<div style="clear:both;"></div>
	<fieldset>
			<label>Agentes: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('agentes')
					->setName('agencia[agentes]')
					->setValue($x->getAgentes())
					->setData('data-campo', '<b>Agentes</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Descripcion: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setMaxlength(300)
					->setType('text')
					->setRows('6')
					->setCols('70')
					->setId('agentes')
					->setName('agencia[descripcion]')
					->setData('data-campo', '<b>Descripcion</b>')
					->setData('data-validator', '{empty:false}')
					->setInnerHtml($x->getDescripcion())
				;
				echo $input->getHtml();
			?> 
			</span>

	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){

})
function validar_agregar_agencia(formData, jqForm, options) {
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		return false;
	}
	return(true);
}
</script>