<?php //es útf8
	$coincidencias = $this->getCoincidencias();
	$coincidencias_seleccionadas = $this->getCoincidenciasSeleccionadas();
?> 
<div class="show_select_coincidencias show_select_coincidencias_paso4">
<ul><?php
	
	$view_mascota = $this->getChild('view_datos_mascota_coincidencia');
//	$childs = $this->getChild();
//	var_dump(array_keys($childs));
//	
	foreach($coincidencias as $coincidencia ){
		//$o = c(new Core_Object())->setData($coincidencia->getData());
		//var_dump($coincidencia->getData('en_id'), $o->getEnId(), get_class($coincidencia));
		//die(__FILE__.__LINE__);
		$mascota = $coincidencia->getMascota(new Frontend_Model_Mascota())->loadNonTableColumn();
		$encuentro = $coincidencia->getEncuentro(new Frontend_Model_Encuentro());
		$seleccionada = in_array($encuentro->getId(), $coincidencias_seleccionadas);

		echo '<li>';
		echo $view_mascota
			->setCoincidencia($coincidencia)
			->setEncuentro($encuentro)
			->setMascota($mascota)
			->setSeleccionada($seleccionada)
			->toHtml()
		;
		//echo $this->getChildHtml('view_datos_mascota');
		echo '</li>';
	}
	
?> 
</ul>
</div>
<script type="text/javascript">
<!--
	jQuery('.link_view_mascota')
		.fancybox({
			'width': 460,
			'height':490,
	        'autoDimensions':true,
	        'transitionIn':'none',
			'transitionOut':'none',
			'type':'iframe'
		})
	;
-->
</script>