<?php //útf8
$object_to_edit = $this->getObjectToEdit();


?>

<div class="addeditmascota_publicacion">
	<form class="standart busqueda" name="form1" method="post">
		<input type="hidden" name="dummy" value="continuar" />
		<div>
			<h2>Datos de Mascota</h2>
			<?php print $this->getChildHtml('view_datos_mascota'); ?>
		</div>
		<div>
			<h2>Ubicación Pérdida</h2>
			<?php print $this->getChildHtml('view_ubicacion_perdida'); ?>
		</div>
		<div>
			<h2>Posibles coincidencias seleccionadas</h2>
			<?php print $this->getChildHtml('view_posibles_reencuentros'); ?>
		</div>
		<div>
			<h2>Opciones de Publicación</h2>
			<?php print $this->getChildHtml('form_edit_publicacion'); ?>
		</div>
		<div class="form_row actions_row single_action">
			<button class="submit button" type="submit">Publicar Anuncio</button>
			<ul>
				<li><a href="#">algun link</a></li>
			</ul>
			<!--
			<ul>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlUpdate()); ?>">Modificar Datos</a></li>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlUpdatePassword()); ?>">Modificar contraseña</a></li>
			</ul>
			<ul>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlServiceConditions()); ?>">Condiciones de Servicio</a></li>
				<li><a href="<?php print $this->getUrl(Frontend_Usuario_Helper::getUrlPrivacyPolicy()); ?>">Políticas de Privacidad</a></li>
			</ul>
			-->
		</div>
	</form>
</div>