<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="audiencia[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):
		echo $this->__t('Nuevo Audiencia');
	else:
		echo $this->__t('Editar Audiencia');
	endif;?></legend>
	<fieldset>
		<h3>Informacion de Audiencia</h3>
		<div>
			<label>Agencia: </label>
			<span><?
				$agencia = new Inta_Model_Agencia();
				$agencias = $agencia->search();
				$html_select = '';
				foreach($agencias as $agencia){
					$option = c(Core::getObject('Core_Html_Tag_Custom', 'option'))
						->setValue($agencia->getId())
						->setInnerHtml($agencia->getNombre())
					;
					if($agencia->getId()==$x->getIdAgencia())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(Core::getObject('Core_Html_Tag_Custom', 'select'))
					->setName('audiencia[id_agencia]')
					->setId('id_agencia')
					->setDisabled('disabled')
					->setInnerHtml($html_select)
					->getHtml()
				;
				
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('hidden')
					->setId('nombre')
					->setName('audiencia[id_agencia]')
					->setValue($x->getIdAgencia())
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Tipo Audiencia: </label>
			<span><?
				echo c($selector_tipo_audiencia = $this->appendBlock('<selector_tipo_audiencia />'))
					->setSelectedValue($x->getIdTipoAudiencia())
					->void($selector_tipo_audiencia
						->getSelectControl()
							->setName('audiencia[id_tipo_audiencia]')
							->setId('id_responsable')
							->setData('data-campo', '<b>Tipo Audiencia</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
					)
					->toHtml()
				;
			?> 
			</span>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('audiencia[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre de Agencia</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<?php if(!$x->getId()): ?>
			<label>Crear Problema:</label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('checkbox')
					->setId('crear_problema')
					//->setName('audiencia[nombre]')
//					->setValue($x->getNombre())
//					->setData('data-campo', '<b>Nombre de Agencia</b>')
//					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<?php endif; ?>
		</div>
	</fieldset><?php 
	if(!$x->getId()):
		$child = c($this->getChild('problema_add_edit_form'))
			->setObjectToEdit(new Core_Object())
			->setAudienciaImplicita(true)
		;
		echo '<div id="contanedor_problema" style="display:none;">';
		echo $child->getHtml();
		echo '</div>';
		?> 
		<script>
			jQuery(document).ready(function(){
				jQuery('#<?php print $child->getFieldsetId(); ?>').setDisable(true);
				jQuery('#crear_problema').change(function(){
					var that = this;
					if(this.checked){
						jQuery('#contanedor_problema').fadeIn('slow', function(){
							jQuery('#<?php print $child->getFieldsetId(); ?>').setDisable(!that.checked);
						});
					}
					else{
						jQuery('#contanedor_problema').fadeOut('slow', function(){
							jQuery('#<?php print $child->getFieldsetId(); ?>').setDisable(!that.checked);
						});
					}
					
				});
			});
		</script><?
	endif;
	
	?> 
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setId('guardar')->setValue('Guardar')->getHtml(); ?>
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('hidden')->setName('continuar')->setValue('0')->getHtml(); ?>
		<?php if(!$x->getId()): ?>
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('button')->setId('continuar')->setValue($this->__t('Cargar Documentos'))->getHtml(); ?>
		<?php endif; ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){
	jQuery('#continuar').click(function(){
		var jqform = jQuery(this).parents('form:first');
		jqform.find('[name=continuar]').val(1);
		jqform.submit();
	});
	jQuery('#guardar').click(function(){
		var jqform = jQuery(this).parents('form:first');
		jqform.find('[name=continuar]').val(0);
		//jqform.submit();//ya es submit este
	});
});

function validar_agregar_audiencia_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>