<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="indicador_resultado[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="indicador_resultado[id_resultado_esperado]" value="<?=$x->getIdResultadoEsperado()?>" />
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> IndicadorResultado</legend>
	<fieldset>
		<div>
			<label>Descripcion: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('descripcion')
					->setName('indicador_resultado[descripcion]')
					->setValue(htmlentities(stripslashes($x->getDescripcion())))
					->setData('data-campo', '<b>Descripcion</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Tipo de Indicador: </label>
			<span><?
			
//				echo c($selector_audiencia = $this->appendBlock('<selector_indicador />'))
//					->setSelectedValue($x->getIdIndicador())
//					->setData('tipo_indicador', 'resultado')
//					->void($selector_audiencia
//						->getSelectControl()
//							->setName('indicador_resultado[id_indicador]')
//							->setId('id_indicador')
//							->setData('data-campo', '<b>Indicador</b>')
//							->setData('data-mensaje', 'Seleccione %field')
//							->setData('data-validator', '{empty:false}')
//					)
//					->toHtml()
//				;
				echo c($selector_audiencia = $this->appendBlock('<selector_indicador_abm />'))
					->setSelectedValue($x->getIdIndicador())
					->setData('tipo_indicador', 'resultado')
					->void($selector_audiencia
						->getSelectControl()
							->setName('indicador_resultado[id_indicador]')
							->setId('id_indicador')
							->setData('data-campo', '<b>Indicador</b>')
							->setData('data-mensaje', 'Seleccione %field')
							->setData('data-validator', '{empty:false}')
							
					)
					->toHtml()
				;

//				$indicador = new Inta_Model_Indicador();
//				$indicadors = $indicador->search();
//				$html_select = '';
//				foreach($indicadors as $indicador){
//					$option = c(Core::getObject('Core_Html_Tag_Custom', 'option'))
//						->setValue($indicador->getId())
//						->setInnerHtml($indicador->getNombre())
//					;
//					if($indicador->getId()==$x->getIdIndicador())
//						$option->setSelected('selected');
//					$html_select .= $option->getHtml();
//				}
//				echo c(Core::getObject('Core_Html_Tag_Custom', 'select'))
//					->setName('indicador_resultado[id_indicador]')
//					->setId('id_indicador')
//					//->setDisabled('disabled')
//					->setInnerHtml($html_select)
//					->getHtml()
//				;
			?> 
			</span>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script type="text/javascript">
function indicador_resultado_enviado(responseText, statusText, xhr, $form){
	//window.console.log({resultado:responseText});<?php 
	if(false&&$this->hasTargetContainer()){?> 
	jQuery('<?php print $this->getTargetContainer(); ?>').html(responseText);<?
	}?> 
	jQuery.ScreenBlock(false);
}
function validar_agregar_indicador_resultado_datos(){
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	var jqwait = jQuery('<div></div>');
	jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
	jqwait.ScreenBlock();

}
</script>